remove node cache
Signed-off-by: LaMavia <tosurowiec@gmail.com>

diff --git a/bin/steps/front b/bin/steps/front
--- a/bin/steps/front
+++ b/bin/steps/front
@@ -10,27 +10,18 @@ install_nodejs() {
     exit 1
   fi
 
-  if [[ -d "$cache_dir/node" ]]; then
-    puts-step "Using cached node"
-    cp -R "$cache_dir/node" "$dir"
-  else 
-    puts-step "Downloading and installing node from $url"
-    code=$(curl "$url" -L --silent --fail --retry 5 --retry-max-time 15 --retry-connrefused --connect-timeout 5 -o /tmp/node.tar.xz --write-out "%{http_code}")
+  puts-step "Downloading and installing node from $url"
+  code=$(curl "$url" -L --silent --fail --retry 5 --retry-max-time 15 --retry-connrefused --connect-timeout 5 -o /tmp/node.tar.xz --write-out "%{http_code}")
 
-    if [ "$code" != "200" ]; then
-      puts-warn "Unable to download node: $code" 
-      exit 1
-    fi
-
-    rm -rf "${dir:?}"/*
-    tar xf /tmp/node.tar.xz --strip-components 1 -C "$dir"
-    chmod +x "$dir"/bin/*
-    mkdir -p "$CACHE_DIR/.heroku" || true
-    cp -R "$dir" "$cache_dir/node"
+  if [ "$code" != "200" ]; then
+    puts-warn "Unable to download node: $code"
+    exit 1
   fi
 
-  
-
+  rm -rf "${dir:?}"/*
+  tar xf /tmp/node.tar.xz --strip-components 1 -C "$dir"
+  chmod +x "$dir"/bin/*
+  mkdir -p "$CACHE_DIR/.heroku" || true
 }
 
 build_front() {
@@ -65,7 +56,7 @@ puts-step "Adding nodejs to PATH"
 export PATH="$NODE_DIR_PATH/bin":$PATH
 
 puts-step "Building front..."
-if ! build_front "$BUILD_DIR/client"; then 
+if ! build_front "$BUILD_DIR/client"; then
   puts-warn "Failed to build front."
   cd "$BUILD_DIR" || exit 1
   exit 1
