revert cd
Signed-off-by: LaMavia <tosurowiec@gmail.com>

diff --git a/bin/steps/front b/bin/steps/front
--- a/bin/steps/front
+++ b/bin/steps/front
@@ -3,41 +3,54 @@
 install_nodejs() {
   local dir="${1:?}"
   local url='https://nodejs.org/dist/v18.15.0/node-v18.15.0-linux-x64.tar.xz'
+  local cache_dir="$CACHE_DIR/.heroku"
 
   if [[ "$STACK" == "heroku-18" ]]; then
     puts-warn "Unsupported heroku stack: $STACK"
     exit 1
   fi
 
-  puts-step "Downloading and installing node from $url"
-  code=$(curl "$url" -L --silent --fail --retry 5 --retry-max-time 15 --retry-connrefused --connect-timeout 5 -o /tmp/node.tar.xz --write-out "%{http_code}")
+  if [[ -d "$cache_dir/node" ]]; then
+    puts-step "Using cached node"
+    cp -R "$cache_dir/node" "$dir"
+  else 
+    puts-step "Downloading and installing node from $url"
+    code=$(curl "$url" -L --silent --fail --retry 5 --retry-max-time 15 --retry-connrefused --connect-timeout 5 -o /tmp/node.tar.xz --write-out "%{http_code}")
 
-  if [ "$code" != "200" ]; then
-    puts-warn "Unable to download node: $code" 
-    exit 1
+    if [ "$code" != "200" ]; then
+      puts-warn "Unable to download node: $code" 
+      exit 1
+    fi
+
+    rm -rf "${dir:?}"/*
+    tar xvf /tmp/node.tar.xz --strip-components 1 -C "$dir"
+    chmod +x "$dir"/bin/*
+    mkdir -p "$CACHE_DIR/.heroku" || true
+    cp -R "$dir" "$cache_dir/node"
   fi
 
-  rm -rf "${dir:?}"/*
-  tar xvf /tmp/node.tar.xz --strip-components 1 -C "$dir"
-  chmod +x "$dir"/bin/*
+  
 
-  mkdir -p "$CACHE_DIR/.heroku" || true
-  cp -R "$dir" "$CACHE_DIR/.heroku"
 }
 
 build_front() {
   local dir="${1:?}"
+  local last_dir
+
+  last_dir="$(pwd)"
 
   cd "$dir" || exit 1
   puts-step "Installing npm dependencies..."
   if ! npm i .; then
     puts-warn "Failed to install npm dependencies."
+    cd "$last_dir" || exit 1
     exit 1
   fi
 
   puts-step "Building client..."
   if ! npm run build; then
     puts-warn "Failed to build client."
+    cd "$last_dir" || exit 1
     exit 1
   fi
 }
